### ISSUE TITLE
More description, a bit of PR?

### ISSUE THREAD

**Issue by pfalcon** [joaompinto/pylibcontainer#8]
Cute project! But what it is? OCI? Runtime Specification? What's that? Perhaps some links in README would help?

Anyway, would you plan to submit it to https://github.com/opencontainers/image-spec/blob/master/implementations.md & https://github.com/opencontainers/runtime-spec/blob/master/implementations.md ?

Thanks.

**Comment by joaompinto** [comment]
I have added a link to the OCI spec in the README. About submitting it to the OCI reference doc, I don't think the current feature set is sufficient to be listed there. 

Thanks for the feedback.
